# Generated by Django 3.2.7 on 2021-11-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='carousel.jpg', upload_to='carouselpix')),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='pix.jpg', upload_to='products')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='pix.jpg', upload_to='products')),
                ('description', models.TextField()),
                ('local', models.BooleanField()),
                ('foreign', models.BooleanField()),
                ('latest', models.BooleanField()),
                ('min', models.IntegerField(default=1)),
                ('max', models.IntegerField(default=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wayapp.category')),
            ],
        ),
    ]
