# Generated by Django 3.2.9 on 2021-11-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0002_auto_20211126_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=10.0),
        ),
    ]
