# Generated by Django 3.2.9 on 2021-11-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0004_member_membership_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Membership',
            field=models.BooleanField(default=False),
        ),
    ]
