# Generated by Django 3.2.9 on 2021-11-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0005_profile_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Membership',
            new_name='Downgrade',
        ),
        migrations.AddField(
            model_name='profile',
            name='Upgrade',
            field=models.BooleanField(default=False),
        ),
    ]
