# Generated by Django 3.2.9 on 2021-12-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='fee',
            field=models.IntegerField(default=1),
        ),
    ]
