# Generated by Django 3.2.9 on 2021-12-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0009_membership_pay_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='pay_code',
            field=models.CharField(max_length=36),
        ),
    ]
