# Generated by Django 3.2.9 on 2021-12-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0012_auto_20211203_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='fee',
        ),
    ]
