# Generated by Django 3.2.9 on 2021-12-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0013_rename_city_profile_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fee',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
