# Generated by Django 3.2.9 on 2021-12-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0016_auto_20211208_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
