# Generated by Django 3.2.9 on 2021-12-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0017_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
