# Generated by Django 3.2.9 on 2021-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0018_rename_username_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member',
            field=models.CharField(default='emma', max_length=50),
        ),
    ]
