# Generated by Django 3.2.9 on 2021-12-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0019_profile_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member',
            field=models.CharField(max_length=50),
        ),
    ]
