# Generated by Django 3.2.9 on 2021-12-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0022_membership_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='memeber_no',
            field=models.CharField(default='1', max_length=36),
        ),
    ]
