# Generated by Django 3.2.9 on 2021-12-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0023_membership_memeber_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='memeber_no',
            field=models.CharField(max_length=36),
        ),
    ]
