# Generated by Django 3.2.9 on 2021-12-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0026_auto_20211210_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='username',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
    ]
