# Generated by Django 3.2.9 on 2021-12-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0028_membership_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership',
            field=models.CharField(max_length=50),
        ),
    ]
